# Generated by Django 6.0 on 2025-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(max_length=255, verbose_name="댓글 id"),
                ),
                (
                    "video_id",
                    models.CharField(max_length=255, verbose_name="동영상 id"),
                ),
                (
                    "authorDisplayName",
                    models.CharField(max_length=100, verbose_name="작성자"),
                ),
                (
                    "authorChannelUrl",
                    models.TextField(blank=True, verbose_name="작성자 채널 주소"),
                ),
                ("textDisplay", models.TextField(blank=True, verbose_name="내용")),
                (
                    "textOriginal",
                    models.TextField(blank=True, verbose_name="내용 원본"),
                ),
                ("likeCount", models.IntegerField(verbose_name="좋아요 수")),
                ("publishedAt", models.DateTimeField(verbose_name="작성일")),
                ("updatedAt", models.DateTimeField(verbose_name="수정일")),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
                "db_table": "comments",
                "ordering": ["-likeCount"],
            },
        ),
    ]
